import smtplib 
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders 
   
fromaddr = "EMAIL address of the sender"
toaddr = "EMAIL address of the receiver"


# instance of MIMEMultipart 
msg = MIMEMultipart() 

fromaddr ='covidquarantineassisstance@gmail.com'
my_password="gocoronago"
# storing the receivers email address  
toaddr='shaunaksaxena@gmail.com'



msg['Subject'] = "maaaro mujhe maaro"
msg["From"]=fromaddr
msg['To']=toaddr


body = "smoke weed everyday"
msg.attach(MIMEText(body, 'plain')) 


# open the file to be sent  
filename = "school_records.csv"
attachment = open(r"C:\Users\user\school_records.csv", "rb") 



# instance of MIMEBase and named as p 
p = MIMEBase('application', 'octet-stream') 
  
# To change the payload into encoded form 
p.set_payload((attachment).read()) 
  
# encode into base64 
encoders.encode_base64(p) 
   
p.add_header('Content-Disposition', "attachment; filename= %s" % filename) 
  
# attach the instance 'p' to instance 'msg' 
msg.attach(p) 





s = smtplib.SMTP_SSL('smtp.gmail.com') 
s.login(fromaddr,my_password)
s.sendmail(fromaddr,toaddr, msg.as_string())
s.quit()
